# Form implementation generated from reading ui file 'c:\Users\k66gu\Documents\m3gan\ui\dialogs\aboutDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(500, 259)
        AboutDialog.setMinimumSize(QtCore.QSize(500, 259))
        AboutDialog.setMaximumSize(QtCore.QSize(500, 259))
        self.okButtonBox = QtWidgets.QDialogButtonBox(AboutDialog)
        self.okButtonBox.setGeometry(QtCore.QRect(210, 210, 81, 31))
        self.okButtonBox.setMinimumSize(QtCore.QSize(81, 31))
        self.okButtonBox.setMaximumSize(QtCore.QSize(81, 31))
        self.okButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.okButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okButtonBox.setObjectName("okButtonBox")
        self.appMetaDataLabel = QtWidgets.QLabel(AboutDialog)
        self.appMetaDataLabel.setGeometry(QtCore.QRect(30, 30, 450, 160))
        self.appMetaDataLabel.setMinimumSize(QtCore.QSize(450, 160))
        self.appMetaDataLabel.setMaximumSize(QtCore.QSize(450, 151))
        self.appMetaDataLabel.setWordWrap(True)
        self.appMetaDataLabel.setObjectName("appMetaDataLabel")
        self.copyrightClogo = QtWidgets.QLabel(AboutDialog)
        self.copyrightClogo.setGeometry(QtCore.QRect(390, 10, 100, 20))
        self.copyrightClogo.setMinimumSize(QtCore.QSize(100, 20))
        self.copyrightClogo.setMaximumSize(QtCore.QSize(100, 20))
        self.copyrightClogo.setObjectName("copyrightClogo")

        self.retranslateUi(AboutDialog)
        self.okButtonBox.accepted.connect(AboutDialog.accept) # type: ignore
        self.okButtonBox.rejected.connect(AboutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About Dialog"))
        self.appMetaDataLabel.setText(_translate("AboutDialog", "appMetaData"))
        self.copyrightClogo.setText(_translate("AboutDialog", "(C) Chris Luu 2023"))
