# Form implementation generated from reading ui file 'c:\Users\k66gu\Documents\m3gan\ui\dialogs\helpDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(600, 450)
        Help.setMinimumSize(QtCore.QSize(600, 450))
        Help.setMaximumSize(QtCore.QSize(600, 450))
        self.okButtonBox = QtWidgets.QDialogButtonBox(Help)
        self.okButtonBox.setGeometry(QtCore.QRect(250, 400, 81, 32))
        self.okButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.okButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okButtonBox.setObjectName("okButtonBox")
        self.textBrowser = QtWidgets.QTextBrowser(Help)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 550, 371))
        self.textBrowser.setMinimumSize(QtCore.QSize(550, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(550, 16777215))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Help)
        self.okButtonBox.accepted.connect(Help.accept) # type: ignore
        self.okButtonBox.rejected.connect(Help.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Help"))
