# Form implementation generated from reading ui file 'c:\Users\k66gu\Documents\m3gan\ui\mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(100, 300, 75, 23))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(200, 300, 75, 23))
        self.stopButton.setObjectName("stopButton")
        self.textEditInput = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditInput.setGeometry(QtCore.QRect(30, 50, 341, 101))
        self.textEditInput.setReadOnly(True)
        self.textEditInput.setObjectName("textEditInput")
        self.textEditOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditOutput.setGeometry(QtCore.QRect(30, 180, 341, 101))
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(140, 10, 121, 31))
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.titleLabel.setObjectName("titleLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.menubar.setObjectName("menubar")
        self.menu_Info = QtWidgets.QMenu(self.menubar)
        self.menu_Info.setObjectName("menu_Info")
        self.menuHistory = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menuHistory.setFont(font)
        self.menuHistory.setObjectName("menuHistory")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.actionHelp.setFont(font)
        self.actionHelp.setObjectName("actionHelp")
        self.menu_Info.addAction(self.actionAbout)
        self.menu_Info.addAction(self.actionHelp)
        self.menubar.addAction(self.menuHistory.menuAction())
        self.menubar.addAction(self.menu_Info.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "M3gan"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.titleLabel.setText(_translate("MainWindow", "M3gan"))
        self.menu_Info.setTitle(_translate("MainWindow", "&Info"))
        self.menuHistory.setTitle(_translate("MainWindow", "History"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
